### PR TITLE
Improve Mixin use case .

### PR DESCRIPTION
**Pull request by JsonSong89**
We can use Intersection Types to declaration the mixed type.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks! But I decided to improve Mixin so users do not need to provide one more type parameter.

Stay tuned.

**Comment by JsonSong89** [comment]
ah , this should be expected !
but how could you omit the mixed?

**Comment by HerringtonDarkholme** [comment]
You can see the new doc. https://github.com/HerringtonDarkholme/av-ts#mixin

**Comment by JsonSong89** [comment]
@HerringtonDarkholme  
Hi，I try to copy and  transplant your mixin design to  [vue-class-component](https://github.com/JsonSong89/vue-class-component)。
Do you mind I create a PR to vue-class-component ?
I will point to this project in readme.

顺便问下，你是华人吗？我很喜欢你的一些项目，交个朋友啊。

**Pull request closed without merging**
