### PR TITLE
[#74] Fix wrong typing caused in #72

### PR DESCRIPTION
**Pull request by whitetrefoil**
I merged some next functions, but I still cannot find proper way to fix:

1. Still have to manually specify `NextFunc` or `NextFuncVm` for `beforeRouteEnter`.
2. Still have to manually specify the generic `MyComponent` for `NextFuncVm<MyComponent>`.
3. Cannot set `this` in `beforeRouteEnter` to `void`:
```typescript
export default class MyPage extends Vue {
  @Prop id = p(String)

  @Lifecycle
  async beforeRouteEnter(to: Route, from: Route, next: NextFuncVm<MyPage>) {
    console.log(this.id) // No `id` on `this` here.
    next((vm) => {
      // `id` can only be referred on `vm`.
      console.log(vm.id)
    })
 }
```

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
As far as I can tell, these 3 items aren't fixable in TypeScript design. I think we should let them be there.

**Comment by whitetrefoil** [comment]
Hoping new features will come in future versions of TS. (although it has already been very complex)

**Comment by whitetrefoil** [comment]
Just found there may have other legal arguments for the next functions, will take a look at them. Hold this PR...

**Comment by whitetrefoil** [comment]
Should I install `vue-router` as dependency then use [`NavigationGuard`](https://github.com/vuejs/vue-router/blob/811846f8ca50be6d550899cee992689e4e7491be/types/router.d.ts#L9) from it directly?

**Comment by whitetrefoil** [comment]
I copied some definition code from vue-router, now the next function can accept different types(callback, `false`, `Location`) of arguments at same time.  (like in README)

**Comment by HerringtonDarkholme** [comment]
I personally prefer code duplication over importing a whole library. Is this pull request good to go?

**Comment by whitetrefoil** [comment]
Me too.  I've tried installing vue-router first, and compiled successfully.

But I had problem when install the compiled code as dependency in other projects - tsc said cannot found stuff av-ts imported from external libs (vue & vue-router).  As a result I cannot test my changes.

So for safety purpose, I copied the code from vue-router instead of import types from it.

**Pull request merged**
